// Date: 16-03-2015 19:45:40
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class modelGreenEdgedTable extends ModelBase
{
  //fields
    ModelRenderer Bordplade;
    ModelRenderer Benstolpe;
    ModelRenderer Bordfod;
  
  public modelGreenEdgedTable()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Bordplade = new ModelRenderer(this, 0, 0);
      Bordplade.addBox(-8F, 0F, -8F, 16, 2, 16);
      Bordplade.setRotationPoint(0F, 8F, 0F);
      Bordplade.setTextureSize(64, 32);
      Bordplade.mirror = true;
      setRotation(Bordplade, 0F, 0F, 0F);
      Benstolpe = new ModelRenderer(this, 0, 0);
      Benstolpe.addBox(-1F, 0F, -1F, 2, 13, 2);
      Benstolpe.setRotationPoint(0F, 10F, 0F);
      Benstolpe.setTextureSize(64, 32);
      Benstolpe.mirror = true;
      setRotation(Benstolpe, 0F, 0F, 0F);
      Bordfod = new ModelRenderer(this, 32, 18);
      Bordfod.addBox(-4F, 0F, -4F, 8, 1, 8);
      Bordfod.setRotationPoint(0F, 23F, 0F);
      Bordfod.setTextureSize(64, 32);
      Bordfod.mirror = true;
      setRotation(Bordfod, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Bordplade.render(f5);
    Benstolpe.render(f5);
    Bordfod.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
